# Stage 1: Configure the base image
# --------------------------------------------------
FROM python:3.12-bookworm AS base
ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache
RUN pip install poetry

# Stage 2: Configure the builder image
# --------------------------------------------------
FROM base AS builder
WORKDIR /app
COPY /apps/server2/poetry.lock .
COPY /apps/server2/pyproject.toml .
COPY /apps/server2/README.md .
RUN --mount=type=cache,id=poetry,target=$POETRY_CACHE_DIR poetry install --without dev --no-root

# Stage 3: Configure and run the runtime image
# # --------------------------------------------------
FROM python:3.12-slim-bookworm AS runtime
WORKDIR /app
ENV PYTHONPATH="$PYTHONPATH:/app" \    
    VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"
COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}
COPY /apps/server2/alembic.ini .
COPY /apps/server2/db/migrations ./db/migrations
COPY /apps/server2/db/models ./db/models
COPY /apps/server2/src ./src
COPY /apps/server2/scripts/startup.sh ./scripts/startup.sh
RUN pip install alembic asyncpg
RUN chmod +x ./scripts/startup.sh
EXPOSE ${PORT}
CMD ["/bin/bash","-c","./scripts/startup.sh"]
